services:
  frontend:
    container_name: MernFrontEND
    build: ./mern/frontend
    ports:
      - "5173:5173"  
    networks:
      - mern
          
  mongodb:
    container_name: MongoDB
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern
    volumes:
      - /opt/mongo-data:/data/db

  backend:
    container_name: MernBackEND
    build: ./mern/backend
    ports:
      - "5050:5050" 
    networks:
      - mern 
    depends_on:
      - mongodb

    
networks:
  mern:
    driver: bridge 
